### PR TITLE
Add Andrew Powerbank Files

### PR DESCRIPTION
**Pull request by Sunsprint**
Fixed symbol library directory name from 'Formula' to 'formula'.

### CODE REVIEW

**Review by iserrato — CHANGES_REQUESTED** [review]
Feedback for PR:
- Great work!
- C1 should not be connected to pin 3 of the connector
- I remember you asking about putting this as close together as possible for the schematic -- yes, it's nice to be concise but not to the point where there is a lack of clarity. Even if things are closer together, they can be harder to read
- As a suggestion, it can be helpful to name the different functional blocks on your schematic so it's easier to refer to

Please change the connection for C1, but besides that awesome job!

**Comment by Sunsprint** [comment]
Placed schematic components onto PCB board.

**Comment by Sunsprint** [comment]
Fixed issues regarding R15, R16 connections, acute trace connections, added via pathways.

R15 is now a 1M pull-up resistor connected to VOUT lines on U3 component after C6, C7 components, before R18. Former +BATT connection to R16 is now +5V. Added vias & pathways connecting +5V, VBUS, BATT+, GND nets.

**Comment by coreyacl** [comment]
Layout Comments:
1. Looks like you have a board-breaking schematic error. C5 and C7 should be providing extra charge by supplying charge referenced from GND. As you have it wired now, you created a high-pass filter by putting the capacitor in series (no bueno) instead of in parallel (mucho bueno). Fix this before anything else.
2. Consider putting a larger copper pour around you USB connectors. More copper around your connector means more structural support so less likely for someone to yank the connector off.
3. If you plan to mount this board into an enclosure, you might find it useful to lineup the front ends of the USB connectors so that they both mate nicely with the wall of enclosure. If you mounted now, your USB type-A will stick out quite a bit.
4. bypass caps: Capacitors that are next to a component in the schematic serve as a low-pass filter so the capacitor should be as close as possible to the component it's bypassing. Resistor placement matters a lot less on this board so I would prioritize cap placement. (All of your caps could be improved)
5. You should add vias for the GND pour between U2 & TP3. Yes the copper pour is technically connected to the vias on the bottom left of that pour but it could be better. This has to do with reducing the parasitic inductance in your current loops by reducing the physical size of the current loop. (More loop more inductance like an inductor). 
6. ALSO: A rule of thumb I've heard that I think applies here is try to have 1 via per GND pin on an IC. So U2 has 5 GND pins, try to have AT LEAST 5 vias to GND for them (Currently I see 2).
7. Speaking of inductors and inductance, don't run any high-frequency traces underneath a capacitor. (C10). And bring that inductor MUCH closer to the IC. You could flip C10 180 degrees and move it with C8 and C9, and bring in L1 close to the IC.
8. Your mounting holes have a weird "REF**" silkcreen on my computer, if you have those too I would just make that invisible or remove the text entirely. Fabhouses don't like impossible tasks like adding silkscreen where board doesn't exist.
9. Seems like a lot of the traces going to U1 are coming from/going to the bottom right of the board. If you had more time I would've suggested starting over and playing around with moving U1 closer to where the traces are coming from. 
10. If you look at the current paths the power will take (Bat -> USB type-A) and (Micro USB -> Bat + USB type-A) it's kinda going all over the place. Given more time I would've recommended trying to tighten those up a bit, especially considering there's a really noisy high-frequency spewing part on this board (the boost converter). I think the board will likely work as is, but would certainly help.
11. Nice job keeping your GND plane pretty clean. Ideally there would be no drops into your GND plane, but that's pretty much impossible with a 2-layer board so a few are expected.
Great job! Shoot me a slack if you have any questions about any of this.

**Pull request merged**
