### PR TITLE
Folder and First pass of schematic

### PR DESCRIPTION
**Pull request by oliviajobradley**

### CODE REVIEW

**Comment by ljordan51** [comment]
@wsh32 this is supposed to require review to merge right?

**Review by jack-greenberg — CHANGES_REQUESTED** [review]
Looks good! I'm gonna leave some comments here:

1. image This is a bit hard to read. It's near the USB LEDs near the FTDI chip
2. I don't think you need net labels for each pin on your microcontroller, unless this is something that @ljordan51 had something in mind for
3. The debug LEDs should have 200Ohm resistors instead of 1ks
4. We'll need to add connectors for the LCD screen. Based off of the [one you chose](https://www.sparkfun.com/products/9052), seems like it'll be a 1x16 pin header, and you'll need to hook up the correct things to the correct places on your microcontroller. we can hop on a call to figure this out together!
5. I'd rename Rx and Tx to be USB_RX and USB_TX
6. Does the FTDI have a 3v3 input on pin 15? if so, we need a linear regulator on there as well to step down 5V to 3v3 (actually seems like we'll need one anyways because the LCD screen operates at 3v3)
7. lol u have a rogue no-connect near the symbol for C3. doesn't do any harm, but might make the electrical rules checker upset

Great job! Thank u for being so flexible with the project as it changes around. I'm more than happy to do a working session where we implement all of these changes together. I'll Slack u :)

**Comment by ljordan51** [comment]
@jack-greenberg 

**Point 2 from your comment:** I agree with you that there is no reason to keep all those net labels. All the unused ones should be replaced with no connect symbols. They will throw an error during the design rule check unless they have no connect symbols or the net labels show up somewhere else making a connection. One of us should probably walk @oliviajobradley through the using the electrical design checklist with this schematic soon and show her how to run the DRC.

**Point 5 from your comment:** The Rx and Tx labels are from the perspective of the ATmega currently. Maybe she should change them to 328p_Rx and 328p_Tx instead?

**Point 6 from your comment:** The FTDI chip creates it's own 3V3 supply. However, there is a different issue here. See my review (soon to follow). [Datasheet](https://www.ftdichip.com/Support/Documents/DataSheets/ICs/DS_FT231X.pdf) for reference.

**Comment by ljordan51** [comment]
Also, we started trying to drill down to the exact power requirements for this board during our feedback session with Manu and Wesley but we need to do some more work there soon. We need to determine how much power the LCD screen will use and then decide how we want this thing to function. Will it always be plugged in? Will the 500mA USB be able to supply the LCD screen, all the LEDs, the 328p operations (usually minimal, less than 10 mA), and the RF receiver? Does it need the option of being handheld and supplied from a battery? This shouldn't stop us from approving this PR but just something to make sure is on our minds moving forward.

**Review by ljordan51 — CHANGES_REQUESTED** [review]
Sorry it's so long! Quick links here:
[DIY Arduino Schematic](https://olinformula.slack.com/files/UBBECD7NH/F01ECAZBRC0/diy_arduino.pdf)
[Redboard schematic that the DIY Arduino was somewhat based on although we missed some things](http://cdn.sparkfun.com/datasheets/Dev/Arduino/Boards/RedBoard-V22.pdf)
[Scroll to the bottom of this confluence page for what's wrong with our DIY arduino schematic](https://docs.olinelectricmotorsports.com/display/AE/Firmware+Revamp)
[FTDI chip datasheet](https://www.ftdichip.com/Support/Documents/DataSheets/ICs/DS_FT231X.pdf)
[My youtube video on reverse voltage protection](https://www.youtube.com/watch?v=1SVR8DVNINw)
[Transistor-Transistor Logic Levels just for fun if you're interested](https://learn.sparkfun.com/tutorials/logic-levels/ttl-logic-levels)
[Digikey link for our LEDs so we can download the datasheet for reference to explain why we use 200 ohm resistors](https://www.digikey.com/en/products/detail/osram-opto-semiconductors-inc/LG-R971-KN-1/1227925?s=N4IgTCBcDaICwHYCsBaAjHNAGdKByAIiALoC%2BQA)

1. All the parts need to be from the formula library. Right now I don't think any of your parts are from the formula library. This is our bad for not communicating this well! Also some of the parts you need don't currently exist in the library so this is a great opportunity to learn how to make parts! We need to check with leadership though to make sure no one else has made or is making them. You should never need any rescue libraries. Any time you see those show up in your project that should be a red flag. You'll need to delete the rescue libraries and remove them from your project. With your project open, right click on each rescue library and then choose "Delete". Then go to Preferences > Manage Symbol Libraries... > Project Specific Libraries and remove each one by clicking on it and then clicking the wastebasket icon at the bottom.

2. Add a 0.1 uF bypass capacitor on the VCC input to the ATmega. Connect one side of the capacitor to VCC and the other side to ground. Place it near the VCC pin so when you go to layout you'll remember that it needs to be physically close to the ATmega VCC pin. Do the same for the FTDI chip.

3. You're going to want to connect your +5V symbol to a power flag. You also want to connect GND to a separate additional power flag. This is just lets KiCAD know they are power symbols. It helps get rid of some errors when doing a design rule check (DRC, the little ladybug button). Just click "a" when hovering on your schematic and type "power flag." You'll need to add 2 to your schematic. 1 to connect to +5V and 1 to connect to GND.

4. You should add reverse (BAT400D-7-F) and overvoltage protection to the USB input. We can help you spec out what kind of protection you should use for each. A zener diode should work for overvoltage. We should see if we have any really low forward voltage schottky diodes (BAT400D-7-F) for reverse voltage protection. Watch [this video](https://www.youtube.com/watch?v=1SVR8DVNINw) for more info. The whole thing is valuable but I don't start specifically talking about overvoltage protection until 9:17.

5. **** See comment 11a and the [Redboard schematic](http://cdn.sparkfun.com/datasheets/Dev/Arduino/Boards/RedBoard-V22.pdf) for resistor/capacitor configuration **** DON'T DO THIS: You should probably add some resistors on the USB lines just to be super safe and make sure you don't run into a situation where you ruin something by allowing too much current to flow to the FTDI chip.

6. Change the IO8 net label that goes to one of your debug leds to something more descriptive like DEBUG_LED or something. Make sure you change it both at the LED and at the ATmega pin it's connected to.

7. Add a power indicator LED for your 5V bus. Basically connect a +5V symbol to a 200 ohm resistor and then to an LED (use LED_0805 from the formula library!). See the [DIY arduino schematic](https://olinformula.slack.com/files/UBBECD7NH/F01ECAZBRC0/diy_arduino.pdf) for more detail if needed.

8. On the FTDI chip, based on the [DIY arduino schematic](https://olinformula.slack.com/files/UBBECD7NH/F01ECAZBRC0/diy_arduino.pdf), 3V3_FTDI should be connected to VCC_IO not VCC. This matches [the FTDI chip datasheet](https://www.ftdichip.com/Support/Documents/DataSheets/ICs/DS_FT231X.pdf) specifications. Since we are supplying the FTDI chip VCC pin with 5V, we can use the 3V3OUT pin to supply the FTDI's own VCCIO. This information is in the datasheet and I'm happy to help show you how to look for it sometime! Quick note, this means that the UART bus will be outputting a 3V3 singal to the ATmega which is okay based on standard TTL (transistor-transistor logic) levels for a 5V bus ([read more here](https://learn.sparkfun.com/tutorials/logic-levels/ttl-logic-levels)). And the FTDI chip will receive a 5V signal from the ATmega, which is also okay because the datasheet says the IO pins can go up to 5.8V safely.

9. According to [the FTDI chip datasheet](https://www.ftdichip.com/Support/Documents/DataSheets/ICs/DS_FT231X.pdf), CBUS1 pulls low when receiving USB data. CBUS2 pulls low when sending USB data. Consider adding a text note by D2 that says something like USB_Rx and similarly, for D4 a note that says USB_Tx. Also you need to change the resistors for both of them to something smaller than 1kohm. Normally we use 200 ohms for these LEDs. I can't find a specification in the datasheet for how much current those inputs can safely sink. All the example schematics in the datasheet show 270 ohm resistors. Let's put 200 ohm resistors there for now but make a note about this on your schematic.

10. Similarly, label your debug leds by adding text notes near them. We usually like to name them based on the pin they are connected to for ease of programming later on. In your case, the labels should be PB5 for D7 and PB0 for D8. You can look at the pin names on the 328p schematic symbol to find this info.

11. The DIY Arduino schematic was not perfect to start and you can find Isabel's and my general comments on it in a comment at the bottom of [this confluence page](https://docs.olinelectricmotorsports.com/display/AE/Firmware+Revamp). I'll note a couple things that definitely relate to your schematic here. If the intention is to program this board over USB (which I think is the intention but I don't know if we have documented the reason why very well), we should probably make sure we copy the [Redboard schematic](http://cdn.sparkfun.com/datasheets/Dev/Arduino/Boards/RedBoard-V22.pdf) which the DIY arduino was based on exactly or make sure we have good understanding of and justification for any differences. For example, the redboard schematic looks like it may be using the DTR pin on the FTDI chip to pull the ATmega RESET low when programming?

11a. All the example applications in the FTDI chip datasheet include 47pF capacitors on the USB lines. The [Redboard schematic](http://cdn.sparkfun.com/datasheets/Dev/Arduino/Boards/RedBoard-V22.pdf) also has these capacitors. I need to do more research to see what exactly their purpose is though.

11b. The [DIY arduino schematic](https://olinformula.slack.com/files/UBBECD7NH/F01ECAZBRC0/diy_arduino.pdf), and as a result your schematic, is missing a pull-up resistor on the reset line of the 328p. Connect one end of a 10k resistor to the RST pin and the other end to +5V. This ensures that your microcontroller doesn't randomly reset unintentionally but can still be reset when needed for programming.

12. Add test points to your schematic for +5V and GND.

**Comment by oliviajobradley** [comment]
I made as many of these changes as I understood, but I'd like to meet with one of you guys to go over the rest, as there is a lot I do not understand.

**Comment by ljordan51** [comment]
Quick note: please annotate your schematic before submitting it for review in the future. There is a little icon at the top of the schematic editor window that looks like a pencil drawing a red line on a paper. It's next to the ladybug. Click the annotate icon. A window will pop up and you can leave all the settings as their defaults. Then click the button at the bottom right of the window: "Annotate." It will automatically change all the "D?", "R?", and "U?", etc. on your schematic to unique identifiers so we can easily identify all the parts on your schematic when giving feedback.

**Comment by ljordan51** [comment]
I can make time at the meeting tonight to start going through everything with you in more detail!

**Comment by oliviajobradley** [comment]
Thanks so much! I uploaded a new version with annotations.

**Comment by ljordan51** [comment]
1. Change VBATT to +5V
2. Flip CBUS1 and CBUS2 LEDs around.
3. Spec a 5-6V Zener diode. Consider speccing a 3.3-3.8V Zener diode for USB lines.

**Comment by ljordan51** [comment]
I added a 5.6V zener diode to our library, D_5.6V_Zener @oliviajobradley

**Pull request closed without merging**
