### PR TITLE
Create kicad project template

### PR DESCRIPTION
**Pull request by wsh32**
Uses B size paper as opposed to A4 from last year, fix inductor and bypass cap connections

image

### CODE REVIEW

**Review by jack-greenberg — CHANGES_REQUESTED** [review]
Looks good! Thanks for including a png. Couple quick things:

* I believe the zener diode should come after the fuse in the buck converter so that a current inrush doesn't damage the diode
  * We changed this a while back but maybe the template board didn't get updated?
* Just out of curiosity, why are we using B sized paper? Not an issue, just wondering

**Comment by wsh32** [comment]
Great catch! we did change it-- i wasnt paying close enough attention when porting teh template board over.

The reasoning for B sized paper is simply because we have B sized paper at Olin. The KiCAD default is A4 (the non-USA/canada standard), we should go with either A size (letter) or B size (11x17), the sizes that we ahve easy access to in case we ever want to print. B size gives more real estate for placing components (i feel like i often feel cramped/struggle to fit entire schematics into letter sized paper). The other thing thats great about B sized is taht it can be printed onto letter paper with 2:1 scaling without any unidirectional stretching

**Comment by wsh32** [comment]
Updated buck converter:

image

**Review by jack-greenberg — APPROVED** [review]
:+1:

**Pull request merged**
