### PR TITLE
feat(telemetry): add CAN Replicator schematic

### PR DESCRIPTION
**Pull request by elviswolcott**
image

The[ application notes](https://www.ftdichip.com/Support/Documents/DataSheets/ICs/DS_FT232R.pdf) for the FTDI show electrolytic caps for the 10nf and 4.7uf. I only saw ceramic in the formula library, and don't know if this is a use case where it matters.
I've also included a generic ferrite bead, as I still need to spec one out.
There's currently not a connector for the CAN bus. I'd like input/suggestions on what connector to use.

### CODE REVIEW

**Comment by elviswolcott** [comment]
image

**Review by jack-greenberg — CHANGES_REQUESTED** [review]
* U3 (USB micro) pin 4 (ID) needs a no-connect
* Specify which pins C7 and C8 need to be placed near
* Is pin 19 of the FTDI (~Reset) supposed to be pulled up? Grounded?
* Only need 3 debug LEDs
* Resistors should come after the debug LEDs
* Should be using 200Ohm resistors for the LEDs

Gotta go cook dinner but those were the main things I saw. Re-request my review when ur done and I'll take another look. Great work Elvis! Just a couple minor things :)

**Comment by ljordan51** [comment]
1. Add over voltage protection. I just added a 5.6V Zener diode to our library. Place it in reverse bias between VCC and GND.
2. Add reverse voltage protection. Place the BAT400D-7-F schottky diode from our library in series with you power supply.
3. Add over current protection. Place the 500mA fuse from our library in series with you power supply and the Zener diode.
4. You can remove all your power flags. The USB connector properly defines its power and GND pins as power outputs. If you leave them you'll get more errors on your DRC (design rule check, ladybug icon). Also the "GND" net label is connected to a power flag but I don't think you use it anywhere else on your schematic. In general, you should just use the GND power symbol and never use a "GND" net label.
5. You need to use the _A pins for programming.
6. Once you move the programming pins to the _A set, you'll need to add series resistance to your USB_RXD and USB_TXD lines to make sure the programmer can always supply more current than them. 500 ohms should do.
7. You need to flip the USB_RXD and USB_TXD connection. USB_TXD should go to the 16m1 RX and USB_RXD should go to the 16m1 TX.
8. Nitpicky: Change all the VCC power symbols to +5V power symbols. Makes it easier to review your schematic when the voltage level is more clear. Also consider adding a note on your schematic near the USB connector that the input voltage can be between 4.4-5.25V. Got this info from the wikipedia page on USB.
9. You need to delete the template-rescue library from your project. With your project open, right click on the rescue library and then choose "Delete". Then go to Preferences > Manage Symbol Libraries... > Project Specific Libraries and remove it by clicking on it and then clicking the wastebasket icon at the bottom.

**Comment by elviswolcott** [comment]
image

**Review by ljordan51 — APPROVED** [review]
great work elvis!

**Comment by elviswolcott** [comment]
[Schematic.pdf](https://github.com/olin-electric-motorsports/AdvancedResearch/files/5960381/Printing.Print.Schematic.pdf)

**Pull request merged**
